# Generated by Django 4.0.2 on 2022-02-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_product_image_product_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
